name: rpaproject
channels:
  - conda-forge
dependencies:
  - python=3.9.16
  - pip=23.0.1
  - pip:
    - rpaframework==22.5.3
    - pandas==2.0.0
    - scikit-learn==1.3.0
    - joblib==1.3.2
    - yfinance==0.2.28
    - xgboost==2.0.0
    - torch==2.1.0
